// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi2ynzp-LIoXbF-7q9Rl88hvCLTFZ4U_A',
    appId: '1:65259633458:android:9148745b4ae397aef5752b',
    messagingSenderId: '65259633458',
    projectId: 'myshp-112d1',
    databaseURL: 'https://myshp-112d1-default-rtdb.firebaseio.com',
    storageBucket: 'myshp-112d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7nyRJdQln-UK9gImeLQSPISCAAFHzzQc',
    appId: '1:65259633458:ios:569e1645fc12ec16f5752b',
    messagingSenderId: '65259633458',
    projectId: 'myshp-112d1',
    databaseURL: 'https://myshp-112d1-default-rtdb.firebaseio.com',
    storageBucket: 'myshp-112d1.appspot.com',
    iosClientId: '65259633458-i9g5u0mlnvftvk9306ek93rm279l7no1.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
